import { Template } from '@/types/docs';

export const templates: Template[] = [
  {
    id: 'meeting-notes',
    name: 'Notas de Reunião',
    description: 'Template para documentar reuniões com agenda e ações',
    category: 'business',
    emoji: '📝',
    elements: [
      { id: '1', type: 'h1', content: 'Notas de Reunião' },
      { id: '2', type: 'h2', content: 'Informações' },
      { id: '3', type: 'text', content: '📅 Data:\n👥 Participantes:\n🎯 Objetivo:' },
      { id: '4', type: 'h2', content: 'Agenda' },
      { id: '5', type: 'list', content: ['Item 1', 'Item 2', 'Item 3'] },
      { id: '6', type: 'h2', content: 'Discussão' },
      { id: '7', type: 'text', content: 'Pontos principais discutidos...' },
      { id: '8', type: 'h2', content: 'Ações' },
      { id: '9', type: 'checklist', content: [
        { id: 'a1', text: 'Ação 1 - Responsável', checked: false },
        { id: 'a2', text: 'Ação 2 - Responsável', checked: false },
      ]},
    ],
  },
  {
    id: 'project-plan',
    name: 'Plano de Projeto',
    description: 'Estrutura completa para planejamento de projetos',
    category: 'business',
    emoji: '🎯',
    elements: [
      { id: '1', type: 'h1', content: 'Plano de Projeto' },
      { id: '2', type: 'h2', content: 'Visão Geral' },
      { id: '3', type: 'text', content: 'Descrição do projeto e objetivos principais.' },
      { id: '4', type: 'h2', content: 'Metas' },
      { id: '5', type: 'checklist', content: [
        { id: 'm1', text: 'Meta 1', checked: false },
        { id: 'm2', text: 'Meta 2', checked: false },
        { id: 'm3', text: 'Meta 3', checked: false },
      ]},
      { id: '6', type: 'h2', content: 'Cronograma' },
      { id: '7', type: 'table', content: {
        headers: ['Fase', 'Início', 'Fim', 'Status'],
        rows: [
          ['Planejamento', '', '', 'Pendente'],
          ['Execução', '', '', 'Pendente'],
          ['Entrega', '', '', 'Pendente'],
        ],
      }},
      { id: '8', type: 'h2', content: 'Recursos' },
      { id: '9', type: 'list', content: ['Equipe', 'Orçamento', 'Ferramentas'] },
    ],
  },
  {
    id: 'personal-goals',
    name: 'Metas Pessoais',
    description: 'Acompanhe suas metas e objetivos pessoais',
    category: 'personal',
    emoji: '🌟',
    elements: [
      { id: '1', type: 'h1', content: 'Minhas Metas' },
      { id: '2', type: 'h2', content: '🎯 Objetivos de Curto Prazo' },
      { id: '3', type: 'checklist', content: [
        { id: 's1', text: 'Meta 1 (este mês)', checked: false },
        { id: 's2', text: 'Meta 2 (este mês)', checked: false },
      ]},
      { id: '4', type: 'h2', content: '🚀 Objetivos de Longo Prazo' },
      { id: '5', type: 'checklist', content: [
        { id: 'l1', text: 'Meta 1 (este ano)', checked: false },
        { id: 'l2', text: 'Meta 2 (este ano)', checked: false },
      ]},
      { id: '6', type: 'h2', content: '💭 Reflexões' },
      { id: '7', type: 'text', content: 'Anote seus pensamentos e progresso...' },
    ],
  },
  {
    id: 'study-notes',
    name: 'Anotações de Estudo',
    description: 'Organize seus estudos e anotações',
    category: 'education',
    emoji: '📚',
    elements: [
      { id: '1', type: 'h1', content: 'Anotações de Estudo' },
      { id: '2', type: 'text', content: '📖 Disciplina:\n📅 Data:\n👨‍🏫 Professor:' },
      { id: '3', type: 'h2', content: 'Conceitos Principais' },
      { id: '4', type: 'list', content: ['Conceito 1', 'Conceito 2', 'Conceito 3'] },
      { id: '5', type: 'h2', content: 'Anotações Detalhadas' },
      { id: '6', type: 'text', content: 'Escreva suas anotações aqui...' },
      { id: '7', type: 'h2', content: 'Exercícios' },
      { id: '8', type: 'checklist', content: [
        { id: 'e1', text: 'Exercício 1', checked: false },
        { id: 'e2', text: 'Exercício 2', checked: false },
      ]},
    ],
  },
  {
    id: 'wiki-page',
    name: 'Página Wiki',
    description: 'Página de documentação estilo wiki',
    category: 'all',
    emoji: '📖',
    elements: [
      { id: '1', type: 'h1', content: 'Título da Página' },
      { id: '2', type: 'text', content: 'Descrição breve do tópico.' },
      { id: '3', type: 'h2', content: 'Introdução' },
      { id: '4', type: 'text', content: 'Conteúdo introdutório...' },
      { id: '5', type: 'h2', content: 'Tópicos' },
      { id: '6', type: 'list', content: ['Tópico 1', 'Tópico 2', 'Tópico 3'] },
      { id: '7', type: 'h2', content: 'Referências' },
      { id: '8', type: 'list', content: ['Referência 1', 'Referência 2'] },
    ],
  },
  {
    id: 'product-spec',
    name: 'Especificação de Produto',
    description: 'Documente especificações de produtos',
    category: 'business',
    emoji: '📋',
    elements: [
      { id: '1', type: 'h1', content: 'Especificação de Produto' },
      { id: '2', type: 'h2', content: 'Visão do Produto' },
      { id: '3', type: 'text', content: 'Descrição geral e proposta de valor.' },
      { id: '4', type: 'h2', content: 'Funcionalidades' },
      { id: '5', type: 'checklist', content: [
        { id: 'f1', text: 'Funcionalidade 1', checked: false },
        { id: 'f2', text: 'Funcionalidade 2', checked: false },
        { id: 'f3', text: 'Funcionalidade 3', checked: false },
      ]},
      { id: '6', type: 'h2', content: 'Requisitos Técnicos' },
      { id: '7', type: 'list', content: ['Requisito 1', 'Requisito 2', 'Requisito 3'] },
      { id: '8', type: 'h2', content: 'Cronograma' },
      { id: '9', type: 'text', content: 'Timeline e milestones...' },
    ],
  },
  {
    id: 'weekly-plan',
    name: 'Planejamento Semanal',
    description: 'Organize sua semana',
    category: 'personal',
    emoji: '📅',
    elements: [
      { id: '1', type: 'h1', content: 'Semana de [Data]' },
      { id: '2', type: 'h2', content: '🎯 Prioridades da Semana' },
      { id: '3', type: 'checklist', content: [
        { id: 'p1', text: 'Prioridade 1', checked: false },
        { id: 'p2', text: 'Prioridade 2', checked: false },
        { id: 'p3', text: 'Prioridade 3', checked: false },
      ]},
      { id: '4', type: 'h2', content: '📋 Tarefas' },
      { id: '5', type: 'checklist', content: [
        { id: 't1', text: 'Tarefa 1', checked: false },
        { id: 't2', text: 'Tarefa 2', checked: false },
        { id: 't3', text: 'Tarefa 3', checked: false },
      ]},
      { id: '6', type: 'h2', content: '📝 Notas' },
      { id: '7', type: 'text', content: 'Anotações adicionais...' },
    ],
  },
  {
    id: 'blank',
    name: 'Página em Branco',
    description: 'Comece do zero',
    category: 'all',
    emoji: '📄',
    elements: [
      { id: '1', type: 'h1', content: 'Nova Página' },
      { id: '2', type: 'text', content: 'Comece a escrever...' },
    ],
  },
];
