import { Task, User, Comment, Activity, TaskTemplate } from '@/types/tasks';

export const sampleUsers: User[] = [
  {
    id: 'user-1',
    name: 'Kleove (você)',
    email: 'kleove@example.com',
    avatar: 'KY',
  },
  {
    id: 'user-2',
    name: 'Maria Silva',
    email: 'maria@example.com',
    avatar: 'MS',
  },
  {
    id: 'user-3',
    name: 'João Santos',
    email: 'joao@example.com',
    avatar: 'JS',
  },
  {
    id: 'user-4',
    name: 'Ana Costa',
    email: 'ana@example.com',
    avatar: 'AC',
  },
];

export const sampleTasks: Task[] = [
  // Tarefas de hoje
  {
    id: 'task-1',
    title: 'Revisar documentação do projeto',
    description: 'Atualizar a documentação técnica com as últimas mudanças',
    status: 'in_progress',
    priority: 'high',
    due_date: new Date().toISOString().split('T')[0], // Hoje
    start_date: new Date(Date.now() - 86400000).toISOString().split('T')[0], // Ontem
    created_at: new Date(Date.now() - 172800000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1'],
    creator_id: 'user-1',
    tag_ids: ['tag-1', 'tag-2'],
    project_id: 'project-1',
    list_id: 'list-1',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista pessoal',
    workspace: 'Espaço da equipe > Projeto 1',
  },
  {
    id: 'task-2',
    title: 'Preparar apresentação para o cliente',
    description: 'Criar slides sobre o progresso do trimestre',
    status: 'todo',
    priority: 'high',
    due_date: new Date().toISOString().split('T')[0], // Hoje
    start_date: null,
    created_at: new Date(Date.now() - 259200000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1', 'user-2'],
    creator_id: 'user-2',
    tag_ids: ['tag-3'],
    project_id: 'project-1',
    list_id: 'list-1',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista pessoal',
    workspace: 'Espaço da equipe > Projeto 1',
  },
  
  // Tarefas em atraso
  {
    id: 'task-3',
    title: 'Corrigir bugs reportados',
    description: 'Lista de bugs críticos que precisam ser corrigidos',
    status: 'todo',
    priority: 'urgent',
    due_date: new Date(Date.now() - 86400000).toISOString().split('T')[0], // Ontem
    start_date: new Date(Date.now() - 259200000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 345600000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1'],
    creator_id: 'user-1',
    tag_ids: ['tag-4'],
    project_id: 'project-2',
    list_id: 'list-2',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista de desenvolvimento',
    workspace: 'Espaço da equipe > Projeto 2',
  },
  {
    id: 'task-4',
    title: 'Atualizar dependências do projeto',
    description: 'Atualizar pacotes npm para versões mais recentes',
    status: 'todo',
    priority: 'medium',
    due_date: new Date(Date.now() - 172800000).toISOString().split('T')[0], // 2 dias atrás
    start_date: null,
    created_at: new Date(Date.now() - 432000000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1'],
    creator_id: 'user-3',
    tag_ids: ['tag-5'],
    project_id: 'project-2',
    list_id: 'list-2',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista técnica',
    workspace: 'Espaço da equipe > Projeto 2',
  },
  
  // Próximas tarefas
  {
    id: 'task-5',
    title: 'Implementar nova funcionalidade de busca',
    description: 'Adicionar busca avançada com filtros',
    status: 'todo',
    priority: 'medium',
    due_date: new Date(Date.now() + 259200000).toISOString().split('T')[0], // 3 dias
    start_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 86400000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1', 'user-3'],
    creator_id: 'user-1',
    tag_ids: ['tag-6'],
    project_id: 'project-1',
    list_id: 'list-1',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista de features',
    workspace: 'Espaço da equipe > Projeto 1',
  },
  {
    id: 'task-6',
    title: 'Realizar testes de performance',
    description: 'Testar tempos de carregamento e otimizações',
    status: 'todo',
    priority: 'low',
    due_date: new Date(Date.now() + 604800000).toISOString().split('T')[0], // 7 dias
    start_date: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1'],
    creator_id: 'user-2',
    tag_ids: ['tag-7'],
    project_id: 'project-1',
    list_id: 'list-3',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista de QA',
    workspace: 'Espaço da equipe > Projeto 1',
  },
  
  // Tarefas não programadas
  {
    id: 'task-7',
    title: 'Pesquisar novas tecnologias',
    description: 'Investigar frameworks modernos para próximo projeto',
    status: 'todo',
    priority: 'low',
    due_date: null,
    start_date: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1'],
    creator_id: 'user-1',
    tag_ids: ['tag-8'],
    project_id: null,
    list_id: 'list-4',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista pessoal',
    workspace: 'Pessoal',
  },
  {
    id: 'task-8',
    title: 'Organizar reunião de planejamento',
    description: 'Agendar com toda a equipe para próximo sprint',
    status: 'todo',
    priority: 'medium',
    due_date: null,
    start_date: null,
    created_at: new Date(Date.now() - 259200000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-1'],
    creator_id: 'user-1',
    tag_ids: ['tag-9'],
    project_id: 'project-1',
    list_id: 'list-1',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista de gestão',
    workspace: 'Espaço da equipe > Projeto 1',
  },
  
  // Tarefas concluídas
  {
    id: 'task-9',
    title: 'Configurar ambiente de desenvolvimento',
    description: 'Setup inicial do projeto com todas as ferramentas',
    status: 'done',
    priority: 'high',
    due_date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    start_date: new Date(Date.now() - 259200000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 432000000).toISOString(),
    completed_at: new Date(Date.now() - 43200000).toISOString(),
    assignee_ids: ['user-1'],
    creator_id: 'user-1',
    tag_ids: ['tag-10'],
    project_id: 'project-2',
    list_id: 'list-2',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista técnica',
    workspace: 'Espaço da equipe > Projeto 2',
  },
  {
    id: 'task-10',
    title: 'Criar wireframes da aplicação',
    description: 'Protótipos de todas as telas principais',
    status: 'done',
    priority: 'medium',
    due_date: new Date(Date.now() - 172800000).toISOString().split('T')[0],
    start_date: new Date(Date.now() - 432000000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 518400000).toISOString(),
    completed_at: new Date(Date.now() - 86400000).toISOString(),
    assignee_ids: ['user-1', 'user-4'],
    creator_id: 'user-4',
    tag_ids: ['tag-11'],
    project_id: 'project-1',
    list_id: 'list-1',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista de design',
    workspace: 'Espaço da equipe > Projeto 1',
  },
  
  // Tarefas delegadas (criadas por user-1, mas atribuídas a outros)
  {
    id: 'task-11',
    title: 'Escrever testes unitários',
    description: 'Cobertura de testes para módulo de autenticação',
    status: 'in_progress',
    priority: 'high',
    due_date: new Date(Date.now() + 172800000).toISOString().split('T')[0],
    start_date: new Date().toISOString().split('T')[0],
    created_at: new Date(Date.now() - 86400000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-3'],
    creator_id: 'user-1',
    tag_ids: ['tag-12'],
    project_id: 'project-2',
    list_id: 'list-2',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista de QA',
    workspace: 'Espaço da equipe > Projeto 2',
  },
  {
    id: 'task-12',
    title: 'Revisar código da feature X',
    description: 'Code review da nova funcionalidade',
    status: 'review',
    priority: 'medium',
    due_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    start_date: new Date().toISOString().split('T')[0],
    created_at: new Date(Date.now() - 172800000).toISOString(),
    completed_at: null,
    assignee_ids: ['user-2'],
    creator_id: 'user-1',
    tag_ids: ['tag-13'],
    project_id: 'project-1',
    list_id: 'list-1',
    parent_task_id: null,
    custom_fields: [],
    location: 'Lista de desenvolvimento',
    workspace: 'Espaço da equipe > Projeto 1',
  },
];

export const sampleComments: Comment[] = [
  {
    id: 'comment-1',
    task_id: 'task-1',
    user_id: 'user-1',
    user_name: 'Kleove (você)',
    text: 'Iniciei a revisão da documentação. Deve estar pronta até o fim do dia.',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    mentions: [],
  },
  {
    id: 'comment-2',
    task_id: 'task-2',
    user_id: 'user-2',
    user_name: 'Maria Silva',
    text: '@Kleove, podemos revisar os slides juntos antes de apresentar?',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    mentions: ['user-1'],
  },
];

export const sampleActivities: Activity[] = [
  {
    id: 'activity-1',
    task_id: 'task-1',
    user_id: 'user-1',
    user_name: 'Kleove (você)',
    action: 'priority_changed',
    details: 'definiu a prioridade como Alta',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'activity-2',
    task_id: 'task-1',
    user_id: 'user-1',
    user_name: 'Kleove (você)',
    action: 'status_changed',
    details: 'alterou o status para Em progresso',
    created_at: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'activity-3',
    task_id: 'task-2',
    user_id: 'user-2',
    user_name: 'Maria Silva',
    action: 'assignee_changed',
    details: 'atribuiu a tarefa para você',
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const taskTemplates: TaskTemplate[] = [
  {
    id: 'template-1',
    name: 'Tarefa Simples',
    description: 'Uma tarefa básica sem subtarefas',
    icon: '📝',
    category: 'geral',
    task: {
      title: 'Nova Tarefa',
      description: '',
      status: 'todo',
      priority: 'medium',
      custom_fields: [],
    },
  },
  {
    id: 'template-2',
    name: 'Bug Report',
    description: 'Template para reportar e corrigir bugs',
    icon: '🐛',
    category: 'ti',
    task: {
      title: 'Bug: ',
      description: '**Descrição do Bug:**\n\n**Passos para Reproduzir:**\n1. \n2. \n3. \n\n**Comportamento Esperado:**\n\n**Comportamento Atual:**\n\n**Screenshots:**\n',
      status: 'todo',
      priority: 'high',
      custom_fields: [
        { id: 'field-1', name: 'Severidade', type: 'select', value: 'crítico', options: ['crítico', 'alto', 'médio', 'baixo'] },
        { id: 'field-2', name: 'Ambiente', type: 'select', value: 'produção', options: ['desenvolvimento', 'staging', 'produção'] },
      ],
      subtasks: [
        { title: 'Investigar causa raiz', status: 'todo', priority: 'high' },
        { title: 'Implementar correção', status: 'todo', priority: 'high' },
        { title: 'Testar correção', status: 'todo', priority: 'high' },
        { title: 'Deploy para produção', status: 'todo', priority: 'medium' },
      ],
    },
  },
  {
    id: 'template-3',
    name: 'Nova Feature',
    description: 'Planejamento e desenvolvimento de nova funcionalidade',
    icon: '✨',
    category: 'trabalho',
    task: {
      title: 'Feature: ',
      description: '**Objetivo:**\n\n**Requisitos:**\n- \n\n**Critérios de Aceitação:**\n- \n\n**Considerações Técnicas:**\n',
      status: 'todo',
      priority: 'medium',
      custom_fields: [
        { id: 'field-3', name: 'Sprint', type: 'text', value: '' },
        { id: 'field-4', name: 'Story Points', type: 'number', value: 0 },
      ],
      subtasks: [
        { title: 'Análise e planejamento', status: 'todo', priority: 'high' },
        { title: 'Design da solução', status: 'todo', priority: 'high' },
        { title: 'Implementação', status: 'todo', priority: 'medium' },
        { title: 'Testes', status: 'todo', priority: 'medium' },
        { title: 'Documentação', status: 'todo', priority: 'low' },
      ],
      checklists: [
        {
          id: 'checklist-1',
          title: 'Checklist de Qualidade',
          items: [
            { id: 'item-1', text: 'Código revisado', checked: false },
            { id: 'item-2', text: 'Testes unitários escritos', checked: false },
            { id: 'item-3', text: 'Documentação atualizada', checked: false },
            { id: 'item-4', text: 'Design aprovado', checked: false },
          ],
        },
      ],
    },
  },
  {
    id: 'template-4',
    name: 'Reunião',
    description: 'Organizar e preparar reuniões',
    icon: '📅',
    category: 'trabalho',
    task: {
      title: 'Reunião: ',
      description: '**Objetivo:**\n\n**Participantes:**\n- \n\n**Agenda:**\n1. \n2. \n3. \n\n**Preparação Necessária:**\n',
      status: 'todo',
      priority: 'medium',
      custom_fields: [
        { id: 'field-5', name: 'Local', type: 'text', value: '' },
        { id: 'field-6', name: 'Duração', type: 'text', value: '1 hora' },
      ],
      subtasks: [
        { title: 'Enviar convite', status: 'todo', priority: 'high' },
        { title: 'Preparar apresentação', status: 'todo', priority: 'medium' },
        { title: 'Enviar ata após reunião', status: 'todo', priority: 'low' },
      ],
    },
  },
  {
    id: 'template-5',
    name: 'Pesquisa',
    description: 'Template para tarefas de pesquisa e análise',
    icon: '🔍',
    category: 'pessoal',
    task: {
      title: 'Pesquisa: ',
      description: '**Tópico:**\n\n**Objetivos:**\n- \n\n**Fontes:**\n- \n\n**Conclusões:**\n',
      status: 'todo',
      priority: 'low',
      custom_fields: [],
      subtasks: [
        { title: 'Definir escopo', status: 'todo', priority: 'medium' },
        { title: 'Coletar informações', status: 'todo', priority: 'medium' },
        { title: 'Analisar dados', status: 'todo', priority: 'medium' },
        { title: 'Documentar resultados', status: 'todo', priority: 'low' },
      ],
    },
  },
  {
    id: 'template-6',
    name: 'Onboarding',
    description: 'Checklist para integração de novos membros',
    icon: '👋',
    category: 'trabalho',
    task: {
      title: 'Onboarding: ',
      description: '**Nome do novo membro:**\n\n**Cargo:**\n\n**Data de início:**\n',
      status: 'todo',
      priority: 'high',
      checklists: [
        {
          id: 'checklist-2',
          title: 'Checklist de Onboarding',
          items: [
            { id: 'item-5', text: 'Configurar conta de email', checked: false },
            { id: 'item-6', text: 'Dar acesso aos sistemas', checked: false },
            { id: 'item-7', text: 'Apresentar à equipe', checked: false },
            { id: 'item-8', text: 'Tour pelo escritório', checked: false },
            { id: 'item-9', text: 'Explicar processos internos', checked: false },
            { id: 'item-10', text: 'Atribuir primeiro projeto', checked: false },
          ],
        },
      ],
    },
  },
  {
    id: 'template-7',
    name: 'Code Review',
    description: 'Template para revisão de código',
    icon: '👀',
    category: 'ti',
    task: {
      title: 'Review: ',
      description: '**Pull Request:**\n\n**Mudanças principais:**\n- \n\n**Pontos de atenção:**\n- \n',
      status: 'review',
      priority: 'high',
      custom_fields: [
        { id: 'field-7', name: 'PR Link', type: 'text', value: '' },
      ],
      checklists: [
        {
          id: 'checklist-3',
          title: 'Checklist de Review',
          items: [
            { id: 'item-11', text: 'Código segue padrões do projeto', checked: false },
            { id: 'item-12', text: 'Não há código duplicado', checked: false },
            { id: 'item-13', text: 'Testes foram adicionados', checked: false },
            { id: 'item-14', text: 'Documentação atualizada', checked: false },
            { id: 'item-15', text: 'Sem vulnerabilidades de segurança', checked: false },
          ],
        },
      ],
    },
  },
  {
    id: 'template-8',
    name: 'Deploy',
    description: 'Checklist para deploy em produção',
    icon: '🚀',
    category: 'ti',
    task: {
      title: 'Deploy: ',
      description: '**Versão:**\n\n**Mudanças:**\n- \n\n**Rollback plan:**\n',
      status: 'todo',
      priority: 'urgent',
      custom_fields: [
        { id: 'field-8', name: 'Ambiente', type: 'select', value: 'produção', options: ['staging', 'produção'] },
      ],
      checklists: [
        {
          id: 'checklist-4',
          title: 'Checklist de Deploy',
          items: [
            { id: 'item-16', text: 'Testes passando', checked: false },
            { id: 'item-17', text: 'Code review aprovado', checked: false },
            { id: 'item-18', text: 'Backup realizado', checked: false },
            { id: 'item-19', text: 'Notificar equipe', checked: false },
            { id: 'item-20', text: 'Deploy executado', checked: false },
            { id: 'item-21', text: 'Smoke tests', checked: false },
            { id: 'item-22', text: 'Monitorar logs', checked: false },
          ],
        },
      ],
    },
  },
];